/**
 * Shadowing content pipeline.
 *
 * Reads a pack manifest, generates one audio file per clip, computes each
 * clip's reference envelope, and emits a seed migration.
 *
 * Usage:
 *   node scripts/shadowing/build-clips.mjs scripts/shadowing/packs/job-interview.json
 *
 * TTS: set SHADOWING_TTS_CMD to a command template that writes an MP3.
 * {{text}} and {{out}} are substituted. Example using piper:
 *   SHADOWING_TTS_CMD='piper --text "{{text}}" --output_file "{{out}}"'
 *
 * Hero clips (those used in ads and on the landing page) are re-recorded by a
 * human afterwards: drop the replacement MP3 over the generated file and re-run
 * with --envelopes-only to recompute envelopes without regenerating audio.
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { basename, join } from 'node:path';

import { extractEnvelope } from '../../packages/core/src/lib/shadowing/envelope.ts';

const manifestPath = process.argv[2];
const envelopesOnly = process.argv.includes('--envelopes-only');

if (!manifestPath) {
  console.error('Usage: node build-clips.mjs <manifest.json> [--envelopes-only]');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const outDir = join('scripts', 'shadowing', 'out', manifest.slug);
mkdirSync(outDir, { recursive: true });

const ttsTemplate = process.env.SHADOWING_TTS_CMD;
if (!envelopesOnly && !ttsTemplate) {
  console.error('SHADOWING_TTS_CMD is not set. See the header of this file.');
  process.exit(1);
}

/** Decode an MP3 to mono Float32 PCM at 16 kHz using ffmpeg. */
function decodeToPcm(mp3Path) {
  const raw = execSync(
    `ffmpeg -v quiet -i "${mp3Path}" -f f32le -ac 1 -ar 16000 -`,
    { maxBuffer: 1024 * 1024 * 64, encoding: 'buffer' },
  );
  return new Float32Array(raw.buffer, raw.byteOffset, Math.floor(raw.length / 4));
}

const rows = [];

manifest.clips.forEach((clip, idx) => {
  const filename = `${String(idx).padStart(2, '0')}.mp3`;
  const outPath = join(outDir, filename);

  if (!envelopesOnly || !existsSync(outPath)) {
    const cmd = ttsTemplate
      .replaceAll('{{text}}', clip.en.replaceAll('"', '\\"'))
      .replaceAll('{{out}}', outPath);
    execSync(cmd, { stdio: 'inherit' });
  }

  const pcm = decodeToPcm(outPath);
  const envelope = extractEnvelope(pcm, 16000);

  rows.push({
    idx,
    textEn: clip.en,
    textVi: clip.vi,
    audioPath: `shadowing/${manifest.slug}/${filename}`,
    durationMs: envelope.durationMs,
    envelope,
  });

  console.log(`[${idx}] ${basename(outPath)}  ${envelope.durationMs}ms`);
});

const sql = `-- 105_shadowing_seed.sql (generated by scripts/shadowing/build-clips.mjs)
-- Pack: ${manifest.slug}
-- Regenerate rather than hand-editing.

DO $$
DECLARE
  v_author uuid;
  v_material uuid;
BEGIN
  SELECT id INTO v_author FROM profiles WHERE role = 'admin' ORDER BY created_at LIMIT 1;
  IF v_author IS NULL THEN
    RAISE EXCEPTION 'no admin profile to own the seeded pack';
  END IF;

  INSERT INTO materials (
    slug, type, level, status, goal,
    title_vi, title_en, summary_vi, summary_en, body_vi, body_en,
    duration_min, gems_reward, xp_reward, author_id, published_at, published_by
  )
  VALUES (
    ${sqlStr(manifest.slug)}, 'shadowing', ${sqlStr(manifest.level)}, 'published', ${sqlStr(manifest.goal)},
    ${sqlStr(manifest.titleVi)}, ${sqlStr(manifest.titleEn)},
    ${sqlStr(manifest.summaryVi)}, ${sqlStr(manifest.summaryEn)},
    ${sqlStr(manifest.bodyVi)}, ${sqlStr(manifest.bodyEn)},
    ${Math.max(1, Math.round(rows.reduce((n, r) => n + r.durationMs, 0) / 60000))},
    0, ${manifest.xpReward}, v_author, now(), v_author
  )
  ON CONFLICT (slug) DO UPDATE SET updated_at = now()
  RETURNING id INTO v_material;

  DELETE FROM shadowing_clips WHERE material_id = v_material;

${rows
  .map(
    (r) => `  INSERT INTO shadowing_clips (material_id, idx, text_en, text_vi, audio_path, duration_ms, reference_envelope)
  VALUES (v_material, ${r.idx}, ${sqlStr(r.textEn)}, ${sqlStr(r.textVi)}, ${sqlStr(r.audioPath)}, ${r.durationMs}, ${sqlStr(JSON.stringify(r.envelope))}::jsonb);`,
  )
  .join('\n')}
END $$;
`;

function sqlStr(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replaceAll("'", "''")}'`;
}

writeFileSync('supabase/migrations/105_shadowing_seed.sql', sql, 'utf8');
console.log(`\nWrote supabase/migrations/105_shadowing_seed.sql (${rows.length} clips)`);
console.log(`Upload ${outDir}/*.mp3 to material-assets under shadowing/${manifest.slug}/`);
