"""Render validated Material objects into idempotent SQL.

Each material is wrapped in its own DO $$ ... $$ block that resolves the author
from the admin profile and inserts the material plus its children. All inserts use
ON CONFLICT DO NOTHING so re-runs are safe. A child failure raises inside the block
and rolls back only that material's inserts.
"""

from __future__ import annotations

import json

from .models import Material


def sql_str(value: str | None) -> str:
    """SQL string literal with single quotes doubled, or NULL."""
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_int(value: int | None) -> str:
    return "NULL" if value is None else str(int(value))


def sql_text_array(items: list[str]) -> str:
    inner = ",".join("'" + s.replace("'", "''") + "'" for s in items)
    return f"ARRAY[{inner}]::text[]"


def _sql_jsonb(meta: dict) -> str:
    return sql_str(json.dumps(meta, ensure_ascii=False)) + "::jsonb"


def _goal_literal(goal: str | None) -> str:
    return "NULL" if goal is None else sql_str(goal)


def render_material(m: Material) -> str:
    """One DO block: material + children, idempotent, author = admin."""
    lines: list[str] = []
    lines.append("DO $$")
    lines.append("DECLARE v_admin uuid;")
    lines.append("BEGIN")
    lines.append("  SELECT id INTO v_admin FROM profiles WHERE role = 'admin' LIMIT 1;")
    lines.append("  IF v_admin IS NULL THEN RAISE NOTICE 'no admin; skipping %', "
                 f"{sql_str(m.slug)}; RETURN; END IF;")
    lines.append("")
    lines.append("  INSERT INTO materials (slug, type, level, status, goal,")
    lines.append("    title_vi, title_en, summary_vi, summary_en, body_vi, body_en,")
    lines.append("    duration_min, gems_reward, xp_reward, min_completion_pct,")
    lines.append("    author_id, published_at, published_by)")
    lines.append("  VALUES (")
    lines.append(f"    {sql_str(m.slug)}, {sql_str(m.type)}, {sql_str(m.level)}, "
                 f"'published', {_goal_literal(m.goal)},")
    lines.append(f"    {sql_str(m.title_vi)}, {sql_str(m.title_en)}, "
                 f"{sql_str(m.summary_vi)}, {sql_str(m.summary_en)},")
    lines.append(f"    {sql_str(m.body_vi)}, {sql_str(m.body_en)},")
    lines.append(f"    {sql_int(m.duration_min)}, {sql_int(m.gems_reward)}, "
                 f"{sql_int(m.xp_reward)}, {sql_int(m.min_completion_pct)},")
    lines.append("    v_admin, now(), v_admin)")
    lines.append("  ON CONFLICT (slug) DO NOTHING;")
    lines.append("")

    if m.type == "vocabulary_pack":
        lines.append("  INSERT INTO vocabulary_items (material_id, idx, term, pos, ipa,")
        lines.append("    vi_phonetic_hint, gloss_vi, gloss_en, example_en, example_vi)")
        lines.append("  SELECT mm.id, v.idx, v.term, v.pos, v.ipa, v.vi_phonetic_hint,")
        lines.append("         v.gloss_vi, v.gloss_en, v.example_en, v.example_vi")
        lines.append("  FROM materials mm, (VALUES")
        rows = []
        for vi in m.vocab_items:
            rows.append(
                "    (" + ", ".join([
                    sql_int(vi.idx), sql_str(vi.term), sql_str(vi.pos), sql_str(vi.ipa),
                    sql_str(vi.vi_phonetic_hint), sql_str(vi.gloss_vi), sql_str(vi.gloss_en),
                    sql_str(vi.example_en), sql_str(vi.example_vi),
                ]) + ")"
            )
        lines.append(",\n".join(rows))
        lines.append("  ) AS v(idx, term, pos, ipa, vi_phonetic_hint, gloss_vi, gloss_en, "
                     "example_en, example_vi)")
        lines.append(f"  WHERE mm.slug = {sql_str(m.slug)}")
        lines.append("  ON CONFLICT (material_id, idx) DO NOTHING;")
    else:
        lines.append("  INSERT INTO material_sections (material_id, idx, kind, body_vi, "
                     "body_en, meta)")
        lines.append("  SELECT mm.id, s.idx, s.kind, s.body_vi, s.body_en, s.meta")
        lines.append("  FROM materials mm, (VALUES")
        rows = []
        for s in m.sections:
            rows.append(
                "    (" + ", ".join([
                    sql_int(s.idx), sql_str(s.kind), sql_str(s.body_vi),
                    sql_str(s.body_en), _sql_jsonb(s.meta),
                ]) + ")"
            )
        lines.append(",\n".join(rows))
        lines.append("  ) AS s(idx, kind, body_vi, body_en, meta)")
        lines.append(f"  WHERE mm.slug = {sql_str(m.slug)}")
        lines.append("  ON CONFLICT (material_id, idx) DO NOTHING;")

    lines.append("END $$;")
    return "\n".join(lines)


def render_file(materials: list[Material]) -> str:
    header = (
        "-- AI-generated materials insert (idempotent).\n"
        "-- Generated by tools/materials-generator. Apply via Supabase MCP execute_sql.\n"
        f"-- Materials: {len(materials)}\n"
    )
    blocks = [render_material(m) for m in materials]
    return header + "\n" + "\n\n".join(blocks) + "\n"
